---
title: "Fitting"
author: "Garrick Bruening"
date: "January 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
#library(ggforce)
library(ggthemes)
library(lmtest)
library(tidyr)
library(dplyr)
library(multcomp)
library(lme4)
library(knitr)
library(grid)
library(gridExtra)
# library(readr)


mpdata <-read.csv('D:/Users/Gary/Desktop/Model Testing/met_power_data.csv')
sumdata <-read.csv('D:/Users/Gary/Desktop/Model Testing/Data_2019.csv')

values <- c('stress','stress2','force','force2','actstate','actstate2','drive','drive2','umberger')
index <- c(1,2,3,4,5,6,7,8,9)
sumdata$minfunc <- values[match(sumdata$minfunc,index)]

minparams = values
fitting_vars = c('sumtorque','sumforce','sumstress','sumactstate','sumdrive','sumumber')
fitting_labs = c('Sum of Torque (Nm)','Sum of Force (N)','Sum of Stress (N/m^2)','Sum of Active State','Sum of Neural Drive','Sum of Energetics (W)')
```


```{r}

# #MPower Net
# MPNet_model_m=nls(metpowernet ~ a5*subjmass + a1 + a2*(effmass2^a3)/(movedur^a4), data=mpdata,start=list(a1=1,a2=1,a3=1,a4=1,a5=1))
# modelsum_m = summary(MPNet_model_m)
# a_m=coef(modelsum_m)[1]
# b_m=coef(modelsum_m)[2]
# c_m=coef(modelsum_m)[3]
# d_m=coef(modelsum_m)[4]
# e_m=coef(modelsum_m)[5]

minfunc1 = values[1]
rsq = c()
minfuncs_rsq = c()
vars_rsq = c()
expo_rsq = c()

# names(rsq_matrix) = c('min_func','variable','expo','rsq')
rsq_matrix = matrix(,nrow=20,ncol=20)
expo=1
count = 0
for (minfunc1 in minparams){
  count = count + 1
  in_count=0
  for (var in fitting_vars){
    in_count = in_count+1
    plotdata=filter(sumdata,minfunc==paste(minfunc1))
    eval(parse(text = paste('fit_',minfunc1,'_',var,'=summary(lm(plotdata$mpowernet ~ plotdata$',var,'))',sep='')))
    
    # print(paste('plot_',minfunc1,'_',var,sep=''))
    
    rsq_val = eval(parse(text=paste('round(fit_',minfunc1,'_',var,'$r.squared,digits = 3)',sep='')))
    titlestr = paste('Min ',minfunc1,', R^2 = ',rsq_val,sep='')
    string = paste('plot_',minfunc1,'_',var,'=ggplot(data=plotdata,aes(x=',var,',y=mpowernet))+geom_point()+geom_smooth(method=\'lm\')+labs(title = \'',titlestr,'\',x =\'',fitting_labs[in_count],'\', y=\'Net Metabolic Power (W)\')+theme(plot.title = element_text(hjust = 0.5))',sep='')
    eval(parse(text = string))
    
    rsq=c(rsq,rsq_val)
    minfuncs_rsq=c(minfuncs_rsq,count)
    vars_rsq = c(vars_rsq,in_count)
    expo_rsq = c(expo_rsq,expo)
    rsq_matrix[count,in_count] = rsq_val
    
  }
    string = paste('groupplot_',minfunc1,'=grid.arrange(plot_',minfunc1,'_','sumtorque,plot_',minfunc1,'_','sumstress,plot_',minfunc1,'_','sumforce,plot_',minfunc1,'_','sumactstate,plot_',minfunc1,'_','sumdrive,plot_',minfunc1,'_','sumumber,nrow=2)',sep='')
    # assign(paste0('groupplot_',minfunc1),eval(parse(text=paste('grid.arrange(plot_',minfunc1,'_','sumtorque,plot_',minfunc1,'_','sumstress,plot_',minfunc1,'_','sumforce,plot_',minfunc1,'_','sumactstate,plot_',minfunc1,'_','sumdrive,plot_',minfunc1,'_','sumumber,nrow=2)',sep=''))))
    eval(parse(text=string))
    
    setwd('d:/Users/Gary/Desktop/Model Testing/2019 Graphs')
    string = paste0('groupplot_',minfunc1,sep='')
    filename = paste0(string,'.pdf')
    plotname = string
    ggsave(filename,get(plotname), useDingbats = FALSE)
}
    
rsq_frame = data.frame(minfunc = minfuncs_rsq,variable=vars_rsq,expo = expo_rsq,rsquared = rsq)

barplot = ggplot(rsq_frame,aes(fill=factor(minfunc),x=factor(variable),y=rsquared))+geom_bar(position='dodge',stat='identity')+scale_x_discrete(labels=fitting_labs)+scale_fill_manual(labels = values, values = colorRampPalette(brewer.pal(9,"Spectral"))(9))+labs(x='Fitted Variable',y='R Squared Value')
setwd('d:/Users/Gary/Desktop/Model Testing/2019 Graphs')
ggsave('grouped_bar_plot.pdf',barplot, useDingbats = FALSE)
```
